### ISSUE TITLE
[Tarefa - 08] - Criação de Swagger

### ISSUE THREAD

**Issue by AntonioAldisio** [fga-eps-mds/2022-2-CAPJu-User#7]
## Descrição.

Desenvolvimento de swagger com as rotas

## Critérios de aceitação

- [ ] Swagger

**Comment by ilus1** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/2022-2-CAPju-6366705c219b67d7df1eab7d/issues/fga-eps-mds/2022-2-CAPJu-User/7?planning-poker) with Zenhub @AntonioAldisio @DaviAntonio @luderibeiro @vitorAlves7
